### ISSUE TITLE
Colorizing log output

### ISSUE THREAD

**Issue by dkisselev** [ngmy/webloyer#33]
I've been testing webloyer out and it looks awesome (thanks for making this happen).

I noticed that the console log output currently just has the ANSI escape codes in it instead of the actual colours. Looks like Sensio actually put out a little library that converts those to HTML colours so we can get full colorization going.

https://github.com/sensiolabs/ansi-to-html

**Comment by ngmy** [comment]
Thanks for the information on the good library!

I have implemented this feature in the PR #34, and released as the version [0.20.0](https://github.com/ngmy/webloyer/releases/tag/0.20.0).
