### ISSUE TITLE
Deploy path on a project level

### ISSUE THREAD

**Issue by paul-blundell** [ngmy/webloyer#50]
Is it possible to set the deploy path on a project level? Instead of in the server yaml?

For example, I have multiple projects that will all be deployed to the same server, in a folder like /var/www/project-name - it would be useful if I could define just the 1 server with the path of /var/www/ and then when I deploy the project it goes into a folder I specify (or a folder of the project name).

**Comment by ngmy** [comment]
It is now impossible.

I will consider whether to add it as a new feature.

**Comment by ngmy** [comment]
I have implemented this feature in the PR #52, and released as the version [0.31.0](https://github.com/ngmy/webloyer/releases/tag/0.31.0).
