### ISSUE TITLE
Deployer Pro

### ISSUE THREAD

**Issue by antonmedv** [ngmy/webloyer#80]
Hi, 

I'm creating deployer pro right now, if you want you can join: https://deployer.org/pro/continuous-integration

**Comment by barryvdh** [comment]
Interesting, subscribed. So similar to Laravel forget etc?

What I'm missing in Forge is the option to easily setup multiple stages for the same project and re-use the server (eg. 1 server with two different directories, same vcs but different branches)

**Comment by antonmedv** [comment]
> multiple stages for the same project and re-use the server

This is possible with deployer.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Hey, is it possible to join the Beta?
My colleague and i using deployer right now but want a web if and thinking about laravel ... but now found your pro version.

thanks

**Comment by antonmedv** [comment]
@mrvnklm write me an email
