### ISSUE TITLE
Trouble with installing

### ISSUE THREAD

**Issue by riartem** [ngmy/webloyer#81]
After installing and running `php artisan webloyer:install` I got exception (see screenshot)

![image](https://user-images.githubusercontent.com/987517/33557093-4628da3c-d917-11e7-96b6-a1621b6c15f2.png)

**Comment by sdukaric** [comment]
Please verify that your local MySQL db is accessible with these credentials. 

In console write: 

mysql -uroot -hlocalhost  webloyer

You should be connected to your local database named webloyer. 

If database does not exist,  make it. 

mysql -uroot -hlocalhost
CREATE database webloyer;

**Comment by ngmy** [comment]
@sdukaric 

Thank you for answering instead of me!
