### ISSUE TITLE
Deployer 6.0.5 php 7.1.13 - webloyer do not release\rollback and show black screened message

### ISSUE THREAD

**Issue by familyman-131** [ngmy/webloyer#83]
Ubuntu 16.04.3 LTS
Deployer 6.0.5
PHP 7.1.13

installed without errors
try to use my working deploy.php, insert it's content to webloyer webinterface - server, and recipe
1. got black screened message http://dl4.joxi.net/drive/2018/01/28/0002/2219/137387/87/7d1c089344.jpg
on any release\rollback actions
and no auth tries from webloyer to testserver in testserver:/var/log/auth.log
how i can debug this error, and is webloyer compatible with Deployer 6.0.5 + PHP 7.1.13?

2. is it possible to use own-hosted ssh-repository, like git@server:repo.git ? i can only add https://github

**Comment by ngmy** [comment]
Hi,

> got black screened message http://dl4.joxi.net/drive/2018/01/28/0002/2219/137387/87/7d1c089344.jpg
> on any release\rollback actions
> and no auth tries from webloyer to testserver in testserver:/var/log/auth.log
> how i can debug this error, and is webloyer compatible with Deployer 6.0.5 + PHP 7.1.13?

Did you execute the following command?
```
nohup php artisan queue:listen --timeout=0 &
```
Webloyer has been tested only with built-in Deployer v4.0.2 and probably works only with it.
If some error has occurred, you can check the Laravel log file (`storage/logs/laravel-yyyy-mm-dd.log`).

> is it possible to use own-hosted ssh-repository, like git@server:repo.git ? i can only add https://github

Please try `ssh://git@server:port/repo.git`.

**Comment by familyman-131** [comment]
`Please try ssh://git@server:port/repo.git.`
yup, this working
`Did you execute the following command?`
yes ofc

probably problem with deployer version, we are working on 6.0.5 now
> local.ERROR: ErrorException: Invalid argument supplied for foreach() in /var/www/webloyer.evergreens.com.ua/www/app/Services/Deployment/DeployerServerListFileBuilder.php:70

waiting for https://deployer.org/pro/continuous-integration ))

thnx for reply

**Comment by vkryukov76** [comment]
@familyman-131 

Every major (and some minor versions too)  of Deployer contains many BC changes

You need change some Webloyer's code to make it works with current Deployer version.

Also you can continue using version 4~. It's pretty stable and covers most of deployment tasks.

**Comment by familyman-131** [comment]
yes, we understand it, thnx

**Comment by ngmy** [comment]
@familyman-131 

I changed the Webloyer program one line and changed my server list YAML file a bit, Webloyer worked with Deployer v6.0.5.

A change of the Webloyer program:

```diff
diff --git a/app/Services/Deployment/DeployerDeploymentFileBuilder.php b/app/Services/Deployment/DeployerDeploymentFileBuilder.php
index 0e1d172..7cf7eab 100644
--- a/app/Services/Deployment/DeployerDeploymentFileBuilder.php
+++ b/app/Services/Deployment/DeployerDeploymentFileBuilder.php
@@ -69,7 +69,7 @@ class DeployerDeploymentFileBuilder implements DeployerFileBuilderInterface
         $contents[] = "set('repository', '{$this->project->repository}');";
 
         // Load a server list file
-        $contents[] = "serverList('{$this->serverListFile->getFullPath()}');";
+        $contents[] = "inventory('{$this->serverListFile->getFullPath()}');";
 
         $this->fs->put($fullPath, implode(PHP_EOL, $contents));
```

It seems that `serverList` function was renamed to `inventory` function.

My server list YAML file before change:

```yaml
stg:
  host: 0.tcp.ngrok.io
  user: nagamiya
  port: 18913
  password: ************
  stage: staging
  deploy_path: /tmp/webloyer
```

My server list YAML file after change:

```yaml
stg:
  hostname: 0.tcp.ngrok.io
  user: nagamiya
  port: 18913
  stage: staging
  deploy_path: /tmp/webloyer
```

I changed a `host` parameter to a `hostname` parameter.
And because a `password` parameter did not work for me, I changed SSH authentication to a key pair instead of a password.

It seems that some specifications of a server list YAML file has been changed.
https://github.com/deployphp/deployer/blob/v6.0.5/test/fixture/inventory.yml

I did not encounter the following error.

> local.ERROR: ErrorException: Invalid argument supplied for foreach() in /var/www/webloyer.evergreens.com.ua/www/app/Services/Deployment/DeployerServerListFileBuilder.php:70

I think that this is caused by your incorrect server list YAML file.

One day I may support the latest version of Deployer.
