### ISSUE TITLE
Issues webloyer installation/usage

### ISSUE THREAD

**Issue by anistor86** [ngmy/webloyer#87]
Hey everyone,
I am trying to you Webloyer, once I understood and managed to make deployer work.
I followed all the installations step without any problem, but as soon as I connect to the webserver, webloyer redirect me to /projects and it throws "Not Found - The requested URL /projects was not found on this server." error!!!

I would just like to log in! I have no projects yet...have you ever faced this issue before?!

**Comment by jraack** [comment]
same issue here. Does not work.

Any directions? Thanks in advance.

**Comment by jraack** [comment]
@anistor86 do you use nginx? if so, check your configuration.

https://laravel.com/docs/6.x/deployment

**Comment by ngmy** [comment]
Hi,

I think this is a problem with your web server.
If you are using nginx, you probably have a misconfigured `try_files` directive.
