### ISSUE TITLE
PHP 7.3 not supported

### ISSUE THREAD

**Issue by BramEsposito** [ngmy/webloyer#88]
Webloyer runs on Laravel 5.2 

This version of Laravel is not compatible with PHP 7.3 (the preg_match call in the validation class is incompatible with PHP 7.3)

I will attempt to update laravel to 5.8.*

**Comment by ngmy** [comment]
Hi,

As a temporary workaround, I've changed Webloyer to not use the validation that call `preg_match()` in PHP 7.3.
This was implemented in #92 and released as the version [0.45.0](https://github.com/ngmy/webloyer/releases/tag/0.45.0).
Webloyer seems to work with PHP 7.3 and 7.4 at the unit test level.

I will upgrade Laravel when I have time.

**Comment by ngmy** [comment]
Probably you will encounter an "Undefined offset" error.
I have released the version [0.45.1](https://github.com/ngmy/webloyer/releases/tag/0.45.1) which fixes this error.
